api_platform:
    title: API du site du MPMEPE
    version: 1.0.0
    show_webby: false
#    eager_loading:
#        max_joins: 30  # La valeur par défaut est 30
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: [ 'multipart/form-data' ]
    collection:
        # The default order of results.
        order: 'DESC'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_enabled: false