twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        sitelink: '%env(SITE_LINK)%'

when@test:
    twig:
        strict_variables: true
